name: Publish package to PyPI.

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish to PyPI.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: 'pip'
          cache-dependency-path: |
            requirements-tests.txt
            requirements.txt
      - name: Build.
        run: |
          python -m pip install --upgrade pip build twine
          python -m build --sdist && python -m build --wheel
      - name: Publish.
        run: |
          twine upload ./dist/* -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}